name: inception

services:

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
    - wordpress
    build: 
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    ports:
     - 443:443
    # Automatically restart this container if Server reboot	/ crash; (manual shutdown/docker stop -> ewmaines stopped
    restart: unless-stopped
    volumes:
      #: Take the volume named wordpress and reflect it in this location inside the container
      - wordpress:/var/www/html
    networks:
      - my-website

  mariadb:
    container_name: mariadb
    image: mariadb
    build: 
      # path for commands in the Dockerfile
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    restart: unless-stopped
    secrets:
      - db-username
      - db-password
      - db-rootpassword
      - db-dbname
    # --connect Active when an external user can connect to the TCP port of MariaDB Server. This strictly tests the TCP connection, not authentication.
    # --innodb_initialized True when InnoDB has completed initializing, including any rollback or crash recover
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping --silent --socket=/run/mysqld/mysqld.sock"]
      interval: 5s
      timeout: 3s
    volumes:
      # the data will be stored on th ehost not just inside a single instance of a running container
      - mariadb:/var/lib/mysql
    networks:
      - my-website
  
  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    build: 
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
    restart: unless-stopped
    secrets:
      - db-username
      - db-password
      - db-dbname
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
      - wp_user
      - wp_user_password
      - wp_user_email
    #makes the env variables available inside the container (for eg. setup.sh)
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_PORT: ${DB_PORT}
    volumes:
      - wordpress:/var/www/html
    networks:
      - my-website

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zpalotas/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zpalotas/data/mariadb

networks:
  my-website:
    name: my-website
    driver: bridge

secrets:
  db-username: 
    file: ../secrets/secret-db_username.txt
  db-password:
    file: ../secrets/secret-db_password.txt
  db-rootpassword:
    file: ../secrets/secret-db_rootpassword.txt
  db-dbname:
    file: ../secrets/secret-db_dbname.txt
  wp_admin_user:
    file: ../secrets/secret-wp_admin_user.txt
  wp_admin_password:
    file: ../secrets/secret-wp_admin_password.txt
  wp_admin_email:
    file: ../secrets/secret-wp_admin_email.txt
  wp_user:
    file: ../secrets/secret-wp_user.txt
  wp_user_password:
    file: ../secrets/secret-wp_user_password.txt
  wp_user_email:
    file: ../secrets/secret-wp_user_email.txt
