server {
    listen 80; 						# listening on port 80

    root /var/www/html; 			# defining the base folder for static file serving
    index index.php; 				# the fallback files checked at folder requests

    location / {					# Match everything that starts with /. => default rulo for all requests
    	try_files $uri $uri/ /index.php;	# checks the request if a file? elif a folder? else serve the index page (internally rewrite request abd send to php-fpm)
	}

    location ~ \.php$ {				# rule for pages ending in php. ~ is a char to introduce regular expressions 
        fastcgi_pass wordpress:9000;	# send request to container named "wordpress" on port 9000 where the php-fpm process is listening
        include fastcgi_params;		# 
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name; 	# defining the path for the pages for the php-fpm also	
    }
}