services:

  nginx:
    container_name: nginx_1
    # would need to use "image:ngnix" if I built from official. Then no Dockerfile needed.
    build: 
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
     - 8080:80
     - 443:443
    # Automatically restart this container if Server reboot	/ crash; (manual shutdown/docker stop -> ewmaines stopped
    restart: unless-stopped
    #env_file: .env
    #environment:
    volumes:
      #: Take the volume named wordpress and reflect it in this location inside the container
      - wordpress:/var/www/html

  db:
    container_name: mariadb_1
    build: 
      # path for commands in the Dockerfile
      context: ./mariadb
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      #- db:/var/lib/mariadb
      # the data will be stored on th ehost not just inside a single instance of a running container
      - db:/var/lib/mysql
  
  wordpress:
    container_name: wordpress_1
    depends_on:
    - db
    build: 
      context: ./wordpress
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
  db: