# one virtual web server. how shoul a specific website be served
server {
	listen 80;
	#NEW
	server_name example.org www.example.org;
	# when looking for files start here. Where are these site's files?
	root /usr/share/nginx/html;
	# id the request is a directory, which file is the default?
	index index.html;

	# for this type of request do this. Chose the most specific that fits
	# / is "match everything" = the default rule
   # location / {
	#	root /usr/share/nginx/html;
   # }
	# check if file exists? if directory exsits? INTERNALLY redirect/rewrite to index.php. then go through locations again
	location / {
		try_files $uri $uri/ /index.php;
	}
	# images are served statically without querying the database or WP. separating nginx and php shows performance improvement here for eg.
    location /images/ {
        root /data;
    }
	# redirect to php server via fastcgi protocol. 
	# it lives on port 9000
	# it will need the parameter SCRIPT_FILENAME which we here set to the request eg: /usr/share/nginx/html/smth.php
	# $document_root = value of the root directive 
	# $fastcgi_script_name = request URI, i.e. “/index.php”. 
	location ~ \.php$ {
        fastcgi_pass  localhost:9000;
        fastcgi_param SCRIPT_FILENAME
                      $document_root$fastcgi_script_name;
        include       fastcgi_params;
    }
}