# an empty settings block bc the configuration expects this to exist but deafults are fine
events {}

# settings that affect every website. default.conf is pasted in here
http {
	##
	# SSL Settings
	##
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;
	
	include /etc/nginx/conf.d/*.conf; #nginx.conf
}

# documentation:
# https://nginx.org/en/docs/