# one virtual web server. how shoul a specific website be served
# processes a request, it first selects the virtual server that will serve the request.
server {
	listen 80 default_server;
	#to decide which server block should handle a request when multiple virtual hosts listen on the same IP and port.
	#"Use this server block when the HTTP Host header matches this name."
	server_name zpalotas.42.fr www.zpalotas.42.fr localhost;
	
	# host is localhost or zpalotas.42.fr
	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl;
	server_name zpalotas.42.fr www.zpalotas.42.fr localhost;

	ssl_certificate /etc/nginx/ssl/zpalotas.crt;
    ssl_certificate_key /etc/nginx/ssl/zpalotas.key;
	ssl_protocols TLSv1.2 TLSv1.3;
	#ssl_prefer_server_ciphers on;

	# when looking for files start here. Where are these site's files?
	root /var/www/html;
		#only used for standalone nginx
		#root /usr/share/nginx/html;
	# id the request is a directory, which file is the default?
	index index.php index.html;

	#LOCATIONS control processing of specific sets of URIs. defines its own scenario of what happens to requests 
		# for this type of request do this. Chose the most specific that fits
		# / is "match everything" = the default rule
		# check if file exists? if directory exsits? INTERNALLY redirect/rewrite to index.php. then go through locations again
	location / {
		try_files $uri $uri/ /index.php;
	}
	# images are served statically without querying the database or WP. separating nginx and php shows performance improvement here for eg.
    location /images/ {
        root /data;
    }
	# redirect to php server via fastcgi protocol. 
		# it lives on port 9000
		# it will need the parameter SCRIPT_FILENAME which we here set to the request eg: /usr/share/nginx/html/smth.php
		# $document_root = value of the root directive (set above)
		# $fastcgi_script_name = request URI, i.e. “/index.php”. 
	location ~ \.php$ {
		# nginx communication method: connects via TCP not unix socket (php8.2-fpm.sock)
  		fastcgi_pass  wordpress:9000;
        fastcgi_param SCRIPT_FILENAME
                      $document_root$fastcgi_script_name;
        include       fastcgi_params;
    }

	#: For setup with WP
		#proxy_set_header Host $host;
		#proxy_set_header X-Real-IP $remote_addr;
	# redirect server error pages to the static page /50x.html
    #
    #error_page   500 502 503 504  /50x.html;
    #location = /50x.html {
    #    root   /usr/share/nginx/html;
    #}
}