daemon off;
# an empty settings block bc the configuration expects this to exist but deafults are fine
events {}

# settings that affect every website. default.conf is pasted in here
http {
	ssl_certificate /etc/nginx/ssl/zpalotas.crt;
    ssl_certificate_key /etc/nginx/ssl/zpalotas.key;

	ssl_protocols TLSv1.2 TLSv1.3;

	#ssl_prefer_server_ciphers on;
	
	include /etc/nginx/conf.d/*.conf; #nginx.conf
}

# documentation:
# https://nginx.org/en/docs/