# A virtual web server defines how a specific website should be served.
# When processing a request, Nginx first selects the virtual server that will serve it.

server {
	listen 443 ssl;
	server_name zpalotas.42.fr www.zpalotas.42.fr localhost;

	ssl_certificate /etc/nginx/ssl/zpalotas.crt;
    ssl_certificate_key /etc/nginx/ssl/zpalotas.key;
	ssl_protocols TLSv1.2 TLSv1.3;

	# Define the base directory for static files. Nginx starts looking for files here.
	root /var/www/html;
	# When a request targets a directory, Nginx checks these files in order.
	index index.php index.html;

	# Locations control the processing of specific URI patterns.
		# Nginx chooses the most specific matching location.
		# The / location matches all requests that do not match a more specific location.
		# Check whether the requested file or directory exists; otherwise, internally route to index.php.
	location / {
		try_files $uri $uri/ /index.php;
	}
	# Serve images directly, without sending requests to WordPress or PHP.
    location /images/ {
        root /data;
    }
	# Forward PHP requests to the PHP-FPM server via FastCGI on port 9000.
		# SCRIPT_FILENAME tells PHP-FPM which script to execute.
		# $document_root is the value of the root directive above.
		# $fastcgi_script_name is the requested script path, for example /index.php.
	location ~ \.php$ {
		# Nginx connects to the WordPress container over TCP instead of a Unix socket.
  		fastcgi_pass  wordpress:9000;	# send request to container named "wordpress" on port 9000 where the php-fpm process is listening
        fastcgi_param SCRIPT_FILENAME
                      $document_root$fastcgi_script_name;	# Define the script path for PHP-FPM.
        include       fastcgi_params;
    }
}