daemon off;
# an empty settings block bc the configuration expects this to exist but deafults are fine
events {}

# settings that affect every website. default.conf is pasted in here
http {
	include /etc/nginx/conf.d/*.conf;
}